# Configuration for local development
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/etalente
    username: user
    password: password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.debug: true
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.ses.SesAutoConfiguration
  cloud:
    aws:
      ses:
        mail:
          enabled: false # Disable SES JavaMailSender when local profile is active

server:
  port: 8080

logging:
  level:
    com.etalente.backend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret-key: YW5vdGhlcmxvbmdzZWNyZXRrZXlmb3Jsb2NhbGRldjQ1Ng==
magic-link-url: http://localhost:4200/auth/callback
invitation-link-url: http://localhost:4200/auth/accept-invitation
invitation-expiry-hours: 72
cors-allowed-origins: http://localhost:4200
