# Configuration for local development with Google SMTP
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com
    from: ${SPRING_MAIL_FROM:your-gmail-address@gmail.com}

logging:
  level:
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG
    com.etalente.backend.service: DEBUG # Exclude SES auto-config when using SMTP