# Development environment configuration
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    show-sql: false

server:
  port: 8080

logging:
  level:
    com.etalente.backend: INFO
    org.springframework.web: INFO

application:
  cors-allowed-origins: ${CORS_ALLOWED_ORIGINS:https://dev.etalente.com}