# Development environment configuration
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    show-sql: false
  mail:
    host: maildev
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.debug: true
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.ses.SesAutoConfiguration
  cloud:
    aws:
      ses:
        mail:
          enabled: false # Disable SES JavaMailSender when dev profile is active

server:
  port: 8080

logging:
  pattern:
    exception-conversion-word: '%xEx{short}'
  level:
    com.etalente.backend: INFO
    org.springframework.web: INFO

cors-allowed-origins: ${CORS_ALLOWED_ORIGINS:https://dev.etalente.com}
invitation-link-url: https://dev.etalente.com/auth/accept-invitation
invitation-expiry-hours: 72
ott:
  expiration-minutes: ${OTT_EXPIRATION_MINUTES:15} # Default for dev
