AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for the Etalente S3 bucket for uploads

Parameters:
  ProjectName:
    Type: String
    Default: etalente
    Description: Name of the project

Resources:
  UploadsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-uploads-${AWS::AccountId}
      # REMOVED: AccessControl: PublicRead (deprecated)
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - PUT
              - GET
              - HEAD
              - POST
              - DELETE
            AllowedOrigins:
              - "http://localhost:4200"
              - "http://etalente-alb-665506398.af-south-1.elb.amazonaws.com"
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-uploads-bucket

  UploadsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UploadsS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${UploadsS3Bucket}/*

Outputs:
  UploadsS3BucketName:
    Description: The name of the S3 bucket for uploads
    Value: !Ref UploadsS3Bucket
    Export:
      Name: !Sub ${ProjectName}-UploadsS3BucketName
  UploadsS3BucketArn:
    Description: The ARN of the S3 bucket for uploads
    Value: !GetAtt UploadsS3Bucket.Arn
    Export:
      Name: !Sub ${ProjectName}-UploadsS3BucketArn